"""initial_schema

Revision ID: f5e1eab0d999
Revises: 
Create Date: 2026-06-06 23:22:44.766981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e1eab0d999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ANALYST', 'ASSOCIATE', 'PARTNER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firm_id'), ['firm_id'], unique=False)

    op.create_table('mandates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SELL_SIDE', 'BUY_SIDE', 'CAPITAL_RAISE', name='mandatetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'CLOSED', 'TERMINATED', name='mandatestatus', native_enum=False), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exchange_rate_date', sa.Date(), nullable=True),
    sa.Column('lead_owner_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['lead_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mandates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mandates_firm_id'), ['firm_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_token')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('hq', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('TARGET', 'BUYER', 'INVESTOR', name='companytype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NOT_CONTACTED', 'CONTACTED', 'RESPONDED', 'INTERESTED', 'DECLINED', 'BOUNCED', name='companystatus', native_enum=False), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('revenue_source', sa.Text(), nullable=True),
    sa.Column('revenue_inr_cr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('relevant_investments', sa.Text(), nullable=True),
    sa.Column('bucket', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('PROPRIETARY', 'PUBLIC', 'REFERRAL', 'IMPORTED', name='source', native_enum=False), nullable=False),
    sa.Column('source_quality', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='sourcequality', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_mandate_id'), ['mandate_id'], unique=False)

    op.create_table('mandate_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandate_id', 'user_id')
    )
    with op.batch_alter_table('mandate_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mandate_assignments_mandate_id'), ['mandate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mandate_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('engagement', sa.Enum('BUY_SIDE', 'SELL_SIDE', 'INVESTOR', 'ADVISOR', 'OTHER', name='engagement', native_enum=False), nullable=True),
    sa.Column('date_connected', sa.Date(), nullable=True),
    sa.Column('mode', sa.Enum('EMAIL', 'CALL', 'LINKEDIN', 'MEETING', 'EVENT', name='contactmode', native_enum=False), nullable=True),
    sa.Column('poc_owner_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['poc_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_firm_id'), ['firm_id'], unique=False)

    op.create_table('outreach_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_INITIAL', 'ACTIVE', 'STOPPED', name='schedulestatus', native_enum=False), nullable=False),
    sa.Column('initial_date', sa.Date(), nullable=True),
    sa.Column('cadence_interval_days', sa.Integer(), nullable=False),
    sa.Column('regarding', sa.Text(), nullable=True),
    sa.Column('stopped_reason', sa.Enum('RESPONDED', 'BOUNCED', 'DECLINED', 'TERMINATED', 'MANUAL', name='stoppedreason', native_enum=False), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('outreach_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_schedules_firm_id'), ['firm_id'], unique=False)

    op.create_table('outreach_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('INITIAL_EMAIL', 'FOLLOW_UP', 'RESPONSE', 'BOUNCE', 'CALL', 'LINKEDIN', 'MEETING', 'NOTE', name='outreacheventtype', native_enum=False), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('regarding', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['outreach_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_events_firm_id'), ['firm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_events_firm_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_events_company_id'))

    op.drop_table('outreach_events')
    with op.batch_alter_table('outreach_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_schedules_firm_id'))

    op.drop_table('outreach_schedules')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_firm_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('mandate_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mandate_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_mandate_assignments_mandate_id'))

    op.drop_table('mandate_assignments')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_mandate_id'))
        batch_op.drop_index(batch_op.f('ix_companies_firm_id'))

    op.drop_table('companies')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('mandates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mandates_firm_id'))

    op.drop_table('mandates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firm_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('firms')
    # ### end Alembic commands ###
